# Generated by Django 4.2.1 on 2023-05-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('razon_social', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Razon Social')),
                ('rut', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Rut')),
                ('direccion', models.CharField(blank=True, default='Desconocido', max_length=100, null=True, verbose_name='Direccion')),
                ('contacto', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contacto')),
                ('correo', models.EmailField(max_length=150, unique=True, verbose_name='Correo Electronico')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'permissions': [],
            },
        ),
    ]
