# Generated by Django 4.2.1 on 2023-05-25 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200, unique=True, verbose_name='Descripcion')),
                ('numero_documento', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': '1.Tipo de Documento',
                'permissions': [],
            },
        ),
        migrations.CreateModel(
            name='TipoVenta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200, unique=True, verbose_name='Descripcion')),
                ('numero_documento', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tipo de Venta',
                'verbose_name_plural': '2.Tipo Venta',
                'permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.PositiveSmallIntegerField()),
                ('fecha_documento', models.DateField(blank=True, null=True)),
                ('hora_recepcion', models.TimeField()),
                ('monto_exento', models.PositiveIntegerField(default=0)),
                ('monto_neto', models.PositiveIntegerField(default=0)),
                ('monto_iva', models.PositiveIntegerField(default=0)),
                ('monto_total', models.PositiveIntegerField(default=0)),
                ('monto_pendiente', models.PositiveIntegerField(default=0)),
                ('monto_pagado', models.PositiveIntegerField(default=0)),
                ('fecha_vencimiento', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.clientes')),
                ('tipo_documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libro.tipodocumento')),
                ('tipo_venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libro.tipoventa')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': '3.Libros',
                'permissions': [],
            },
        ),
        migrations.CreateModel(
            name='ConciliacionPagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_registro', models.PositiveSmallIntegerField()),
                ('fecha_de_Pago', models.DateField()),
                ('monto_pagado', models.PositiveIntegerField()),
                ('fecha_conciliacion', models.DateField()),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libro.libro')),
            ],
            options={
                'verbose_name': 'ConciliacionPago',
                'verbose_name_plural': '4.ConciliacionPagos',
                'permissions': [],
            },
        ),
    ]
